### ISSUE TITLE
Error compiling the code

### ISSUE THREAD

**Issue by blowfish2003** [catid/TimeSync#4]
Hi,

I am getting many errors during code compilation using cmake. Here is one of the errors:

error: explicit specialization in non-namespace scope ‘class Counter<T, TkBits>’

I have cmake 3.7.2 and g++ 6.3.0 on the system on which I am attempting to compile

**Comment by catid** [comment]
Okay should just need to throw in some typenames to get it to build for
you.  I'll do it next time there's some free time

**Comment by blowfish2003** [comment]
Thanks. Will try to do it locally.
