### ISSUE TITLE
Do I have to send both: LocalTimeToDatagramTS24 and ToRemoteTime23 ?

### ISSUE THREAD

**Issue by sevenuz** [catid/TimeSync#6]
Should I always send TimeSynchronizer::LocalTimeToDatagramTS24(nowUsec) to improve synchronization,
but also ToRemoteTime23(uint64_t localUsec) to work with in my application?

Or can I use one for both? 

Thx :)

**Comment by catid** [comment]
ToRemoteTime23() would be the function to use to generate 3 bytes to put in a packet you send, so that the peer can call FromLocalTime23() to decode back to a full 64-bit timestamp.

LocalTimeToDatagramTS24() generates the 3 bytes in local time rather than peer's time

**Comment by sevenuz** [comment]
Thank you for the answer. So I can not use one timestamp? :D I also do not understand the difference between peer time and local time when they are already synchronized. Shouldn't be the same or are they using OWD already?
Sorry that I don't get it :/
I am now sending LocalTimeToDatagramTS24 to pass to OnAuthenticatedDatagramTimestamp to increase precision but also ToRemoteTime23 to work with in my application...
